import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Md Adib Mannan",
  description: "Generated by create next aAs a professional web developer with extensive experience in both front-end and back-end development, I specialize in creating dynamic, responsive websites that deliver exceptional user experiences. Proficient in HTML5, CSS3, and JavaScript, I leverage frameworks like React, Angular, and Vue.js for interactive front-end design. My back-end expertise includes Node.js, Python, and PHP, along with robust database management using MongoDB. I also excel in SEO optimization, ensuring your website ranks highly on search engines through strategic keyword research, on-page SEO, and technical SEO. By integrating these elements, I build websites that not only look impressive but also drive organic traffic and achieve business goals. Let's collaborate to enhance your digital presence with cutting-edge web solutions. Visit my portfolio for more information",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} bg-dark text-light`}>
        {/* <Navbar/> */}
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
